services:
  api:
    image: ghcr.io/foederierter-datenpool/directory-api:main
    pull_policy: always
    environment:
      SPRING_APPLICATION_NAME: sosuse-api
    mem_limit: 512m
    restart: unless-stopped
