services:
  api:
    image: &directory-image sosuse-directory-api:local
    pull_policy: never
    build:
      context: .
      no_cache: true
      pull: true
      args:
        SNAPSHOT_URL: https://codeload.github.com/foederierter-datenpool/sosuse-directory-builder/tar.gz/refs/heads/pipeline-data
    environment:
      SPRING_APPLICATION_NAME: sosuse-api
      DIRECTORY_API_FILE: /app/snapshot/data/directory.ttl
      DIRECTORY_API_SPARQL_URL: http://fuseki:3030/directory/sparql
    mem_limit: 512m
    restart: unless-stopped

  fuseki:
    image: *directory-image
    pull_policy: never
    entrypoint: ["java", "-jar", "/app/fuseki/directory-fuseki.jar"]
    command: ["/app/snapshot"]
    mem_limit: 512m
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "--fail", "--silent", "http://localhost:3030/directory/sparql?query=ASK%7B%7D"]
